matrix:
  include:
    - language: sh
      os:
        - linux
      env:
        - PWSH_VERSION=6.1.2
        - PWSH_OS=linux
      before_script:
        - chmod +x ./install_pwsh.sh
        - ./install_pwsh.sh
      script:
        - which pwsh
        - pwsh -c \$PSVersionTable
    - language: sh
      os:
        - osx
      env:
        - PWSH_VERSION=6.1.2
        - PWSH_OS=osx
      before_script:
        - chmod +x ./install_pwsh.sh
        - ./install_pwsh.sh
      script:
        - which pwsh
        - pwsh -c \$PSVersionTable
