matrix:
  include:
    - language: sh
      os:
        - linux
      before_script:
        - chmod +x ./ci/install_unix.sh
        - ./ci/install_unix.sh
      script:
        - pwsh -c \$PSVersionTable
    - language: sh
      os:
        - osx
      before_script:
        - chmod +x ./ci/install_unix.sh
        - ./ci/install_unix.sh
      script:
        - pwsh -c \$PSVersionTable
